module RescueGroupsV5
  module Fields
    module Animal
      FIELDS = %w[
        id
        activityLevel
        adoptedDate
        adoptionFee
        isAdoptionPending
        adultSexesOk
        ageGroup
        age
        isAltered
        availableDate
        birthDate
        isBirthDateExact
        breedId
        breed
        breedPrimary
        breedPrimaryId
        breedSecondary
        breedSecondaryId
        isBreedMixed
        isCatsOk
        coatLength
        color
        colorId
        colorDetails
        isCourtesyListing
        isCurrentVaccinations
        isDeclawed
        descriptionHtml
        descriptionText
        distinguishingMarks
        isDogsOk
        earType
        energyLevel
        eventsAttendingCount
        exerciseNeeds
        eyeColor
        fenceNeeds
        isNeedingFoster
        isFound
        foundDate
        foundPostalcode
        groomingNeeds
        priority
        isHousetrained
        housetrainedReasonNot
        indoorOutdoor
        isKidsOk
        killDate
        killReason
        isMicrochipped
        name
        newPeopleReaction
        obedienceTraining
        ownerExperience
        pattern
        patternId
        pictureCount
        pictureThumbnailUrl
        qualities
        rescueId
        search
        sex
        sheddingLevel
        sizeCurrent
        sizeGroup
        sizePotential
        sizeUOM
        slug
        isSpecialNeeds
        specialNeedsDetails
        species
        speciesId
        isSponsorable
        sponsors
        sponsorshipDetails
        sponsorshipMinimum
        summary
        tailType
        url
        videoCount
        videoUrlCount
        vocalLevel
        isYardRequired
        createdDate
        updatedDate
      ]
    end
  end
end
