# frozen_string_literal: true

module RescueGroupsV5
  module Fields
    module Animal
      FIELDS = %w[
        activityLevel
        adoptedDate
        adoptionFeeString
        adultSexesOk
        ageGroup
        availableDate
        birthDate
        breedPrimary
        breedPrimaryId
        breedSecondary
        breedSecondaryId
        coatLength
        colorDetails
        createdDate
        descriptionHtml
        descriptionText
        distinguishingMarks
        earType
        energyLevel
        exerciseNeeds
        eyeColor
        fenceNeeds
        foundDate
        foundPostalcode
        groomingNeeds
        housetrainedReasonNot
        id
        indoorOutdoor
        isAdoptionPending
        isAltered
        isBirthDateExact
        isBreedMixed
        isCatsOk
        isCourtesyListing
        isCurrentVaccinations
        isDeclawed
        isDogsOk
        isFarmAnimalsOk
        isFound
        isHousetrained
        isKidsOk
        isMicrochipped
        isNeedingFoster
        isSpecialNeeds
        isSponsorable
        isYardRequired
        killDate
        killReason
        name
        newPeopleReaction
        obedienceTraining
        ownerExperience
        pictureCount
        pictureThumbnailUrl
        priority
        qualities
        rescueId
        searchString
        sex
        sheddingLevel
        sizeCurrent
        sizeGroup
        sizePotential
        sizeUOM
        slug
        specialNeedsDetails
        sponsors
        sponsorshipDetails
        sponsorshipMinimum
        summary
        tailType
        trackerimageUrl
        updatedDate
        url
        videoCount
        videoUrlCount
        vocalLevel
      ].freeze
    end
  end
end
